MaxBranzburg/rails_games/config/routes.rb
Games::Application.routes.draw do

  root 'games#index'
  
  resources "games", only: [:index]
  resources "secret_numbers", only: [:new, :show]
  resources "rock_paper_scissors", only: [:new, :show]

end

MaxBranzburg/rails_games/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

MaxBranzburg/rails_games/app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
  def new
  	@throws = ["Rock", "Paper", "Scissors"]
  end

  def show
  	@throws = ["Rock", "Paper", "Scissors"]
  	@user_throw = @throws[params[:id].to_i]
  	@comp_throw = @throws.sample
  	@result = get_results(@user_throw, @comp_throw)
  end

  def get_results(user_throw, comp_throw)
  	if @user_throw == @comp_throw
  		'tie'
  	elsif @user_throw == "Rock" && @comp_throw == "Paper"
  		'lose'
   	elsif @user_throw == "Rock" && @comp_throw == "Scissors"
  		'win'
  	elsif @user_throw == "Paper" && @comp_throw == "Scissors"
  		'lose'
   	elsif @user_throw == "Paper" && @comp_throw == "Rock"
  		'win'
  	elsif @user_throw == "Scissors" && @comp_throw == "Rock"
  		'lose'
   	elsif @user_throw == "Scissors" && @comp_throw == "Paper"
  		'win'
  	end
  end

end

MaxBranzburg/rails_games/app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
  def new
  end

  def show
    @chosen_number = params[:id].to_i
    @secret_number = rand(1..5)
    @player_won = (@chosen_number == @secret_number)

    if @player_won
      @outcome_partial = 'win'
    else
      @outcome_partial = 'lose'
    end
  end
end

MaxBranzburg/rails_games/app/helpers/games_helper.rb
module GamesHelper
end

MaxBranzburg/rails_games/app/helpers/rock_paper_scissors_helper.rb
module RockPaperScissorsHelper
end

MaxBranzburg/rails_games/app/helpers/secret_numbers_helper.rb
module SecretNumbersHelper
end

MaxBranzburg/rails_games/app/views/games/index.html.erb
<h1>Welcome to BEWD Games!</h1>

<div><%= link_to 'Play Secret Number!', new_secret_number_path %></div>
<div><%= link_to 'Play Rock Paper Scissors!', new_rock_paper_scissor_path %></div>

MaxBranzburg/rails_games/app/views/rock_paper_scissors/_lose.html.erb
<h1>You suck!</h1>
<p>You threw a <em><%= @user_throw %></em></p>
<p>I threw a <em><%= @comp_throw %></em></p>
<p>Therefore...</p>

<p>You lost the game!</p>

MaxBranzburg/rails_games/app/views/rock_paper_scissors/_tie.html.erb
<h1>You're just okay!</h1>
<p>You threw a <em><%= @user_throw %></em></p>
<p>I threw a <em><%= @comp_throw %></em></p>
<p>Therefore...</p>

<p>You tied the game!</p>

MaxBranzburg/rails_games/app/views/rock_paper_scissors/_win.html.erb
<h1>You're amazing!</h1>
<p>You threw a <em><%= @user_throw %></em></p>
<p>I threw a <em><%= @comp_throw %></em></p>
<p>Therefore...</p>

<p>You won the game. You're a hero!</p>

MaxBranzburg/rails_games/app/views/rock_paper_scissors/new.html.erb
<h1>Welcome to Rock Paper Scissors!</h1>

<p>To play this game, pick <em>Rock</em>, <em>Paper</em>, or <em>Scissors</em>. The computer will throw against you, and results are as follows:

<ul>
	<li>Rock beats scissors</li>
	<li>Scissors beats paper</li>
	<li>Paper beats rock</li>
	<li>Same throws tie and user plays again</li>
</ul>

<p>Choose carefully:</p>

<ul>
	<table>
		<tr>
			<% @throws.each_with_index do |throw, num| %>
				<td><%= link_to image_tag("#{throw}.jpg", :height => 100), rock_paper_scissor_path(num) %></td>
			<% end %>
		</tr>
	</table>
</ul>

MaxBranzburg/rails_games/app/views/rock_paper_scissors/show.html.erb
<%= render @result %>

<p><%= link_to "Play Again?", new_rock_paper_scissor_path %></p>

MaxBranzburg/rails_games/app/views/secret_numbers/_lose.html.erb
<h1>Sorry, you lost the game.</h1>
<p>You should yell, "I'm awesome!"</p>

MaxBranzburg/rails_games/app/views/secret_numbers/_win.html.erb
<h1>You're amazing!</h1>
<p>You won the game. You're a hero!<p>

MaxBranzburg/rails_games/app/views/secret_numbers/new.html.erb
<h1>Welcome to Secret Number!</h1>

<p>To play this game, all you have to do is guess a number. If you guess the <em>secret number</em>, you win!</p>

<p>Choose carefully... you only get one try!</p>

<h2>Pick a number:</h2>

<ul>
<% (1..5).each do |number| %>
  <li><%= link_to number, secret_number_path(number) %></li>
<% end %>
</ul>

MaxBranzburg/rails_games/app/views/secret_numbers/show.html.erb
<%= render @outcome_partial %>

<h4>The secret number was <%= @secret_number %></h4>

<h3><%= link_to "PLAY AGAIN", new_secret_number_path %></h3>