johnfohr-jofo45/08_class_rails/games/config/routes.rb
Games::Application.routes.draw do
  get 'rock_paper_scissors/new'

  get 'rock_paper_scissors/show'

  get 'rock_paper_scissors/index'

  root 'games#index'
  
  resources 'games', only: [:index]
  resources "secret_numbers", only: [:new, :show]
end

johnfohr-jofo45/08_class_rails/games/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

johnfohr-jofo45/08_class_rails/games/app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
  def index
  end

  def show
     tie = false
    @throws = ["rock", "paper", "scissors"]
    user_throw = @throws[params[:id]]
    comp_throw = @throws.sample

    if user_throw = comp_throw
      tie == true
      win == false
    elsif user_throw == "paper" && comp_throw == "scissors"
      win == false
    elsif user_throw == "rock" && comp_throw == "scissors"
      win == true
  elsif user_throw == "paper" && comp_throw == "rock"
      win == true
  elsif user_throw == "rock" && comp_throw == "paper"
      win == false
  elsif user_throw == "scissors" && comp_throw == "rock"
      win == false
  else #user_throw == "scissors" && comp_throw == "paper"
      win == true
  end
  end

  def new
end
end

johnfohr-jofo45/08_class_rails/games/app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
  def new
  end

  def show
    @chosen_number = params[:id].to_i
    @secret_number = rand(1..5)
    @player_won = (@chosen_number == @secret_number)

    if @player_won
      @outcome_partial = 'win'
    else
      @outcome_partial = 'lose'
    end
  end
end

johnfohr-jofo45/08_class_rails/games/app/helpers/games_helper.rb
module GamesHelper
end

johnfohr-jofo45/08_class_rails/games/app/helpers/rock_paper_scissors_helper.rb
module RockPaperScissorsHelper
end

johnfohr-jofo45/08_class_rails/games/app/helpers/secret_numbers_helper.rb
module SecretNumbersHelper
end

johnfohr-jofo45/08_class_rails/games/app/views/games/index.html.erb
<h1>Welcome to BEWD Games!</h1>

<div><%= link_to 'Play Secret Number!', new_secret_number_path %></div>
<div><%= link_to 'Play Rock Paper Scissors!', new_rock_paper_scissors_path %></div>

johnfohr-jofo45/08_class_rails/games/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

johnfohr-jofo45/08_class_rails/games/app/views/rock_paper_scissors/index.html.erb
<h1>RockPaperScissors#index</h1>
<p>Find me in app/views/rock_paper_scissors/index.html.erb</p>

johnfohr-jofo45/08_class_rails/games/app/views/rock_paper_scissors/new.html.erb
<h1>RockPaperScissors#new</h1>
<p>Find me in app/views/rock_paper_scissors/new.html.erb</p>


<h2>Choose cafefully! (R)ock, (P)aper, (S)cissors:</h2>
<!-- 
<ul>
<% @throws.each do |choice| %>
  <li><%= link_to choice, rock_paper_scissors_show_path(choice) %></li>
<% end %>
</ul> -->

johnfohr-jofo45/08_class_rails/games/app/views/rock_paper_scissors/show.html.erb
<h1>RockPaperScissors#show</h1>
<p>Find me in app/views/rock_paper_scissors/show.html.erb</p>


  	if win == true
  	<p>	"Good job" </p>
    elsif tie = true
    <p> "yikes a tie!" </p>
	  else  #win == false
	<p>	"You lost" </p>
	